// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.donation.eoy.version.viewed", 5);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1735370402);
user_pref("app.update.lastUpdateTime.region-update-timer", 1735370402);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1735370402);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1731136950);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1735370402);
user_pref("browser.region.update.updated", 1735370403);
user_pref("browser.search.region", "IN");
user_pref("calendar.caldav.googleResync", 1731136891);
user_pref("calendar.list.sortOrder", "f8d9cb49-a25b-4150-855d-a8369cefb70d");
user_pref("calendar.registry.f8d9cb49-a25b-4150-855d-a8369cefb70d.calendar-main-default", true);
user_pref("calendar.registry.f8d9cb49-a25b-4150-855d-a8369cefb70d.calendar-main-in-composite", true);
user_pref("calendar.registry.f8d9cb49-a25b-4150-855d-a8369cefb70d.disabled", true);
user_pref("calendar.registry.f8d9cb49-a25b-4150-855d-a8369cefb70d.name", "Home");
user_pref("calendar.registry.f8d9cb49-a25b-4150-855d-a8369cefb70d.type", "storage");
user_pref("calendar.registry.f8d9cb49-a25b-4150-855d-a8369cefb70d.uri", "moz-storage-calendar://");
user_pref("calendar.timezone.local", "Asia/Kolkata");
user_pref("calendar.timezone.useSystemTimezone", true);
user_pref("calendar.ui.version", 3);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1731136901176");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 35);
user_pref("extensions.getAddons.cache.lastUpdate", 1735370402);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.lastAppBuildId", "20241009170210");
user_pref("extensions.lastAppVersion", "115.16.0");
user_pref("extensions.lastPlatformVersion", "115.16.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webextensions.uuids", "{\"default-theme@mozilla.org\":\"d550df54-58eb-45d3-a7c8-015cd2349645\",\"google@search.mozilla.org\":\"9f83226f-5a65-457c-a7d6-995367c21344\",\"ddg@search.mozilla.org\":\"9b8abe6b-74df-495e-a3f0-1e31128a0b81\",\"amazondotcom@search.mozilla.org\":\"19f32aaa-a67f-46c3-98a0-3665cb9ffc13\",\"wikipedia@search.mozilla.org\":\"da628ac5-9e1f-410a-8240-82156743ed4a\",\"bing@search.mozilla.org\":\"15c15969-20aa-4d14-a3fd-fc4e76b25282\"}");
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("idle.lastDailyNotification", 1735370957);
user_pref("mail.ab_remote_content.migrated", 1);
user_pref("mail.ui-rdf.version", 40);
user_pref("mailnews.database.global.datastore.id", "73930d0e-fdd2-44fd-baf9-f0c21867f44");
user_pref("mailnews.headers.extraAddonHeaders", "autocrypt openpgp");
user_pref("mailnews.quotingPrefs.version", 1);
user_pref("mailnews.start_page_override.mstone", "115.16.0");
user_pref("mailnews.tags.$label1.color", "#FF0000");
user_pref("mailnews.tags.$label1.tag", "Important");
user_pref("mailnews.tags.$label2.color", "#FF9900");
user_pref("mailnews.tags.$label2.tag", "Work");
user_pref("mailnews.tags.$label3.color", "#009900");
user_pref("mailnews.tags.$label3.tag", "Personal");
user_pref("mailnews.tags.$label4.color", "#3333FF");
user_pref("mailnews.tags.$label4.tag", "To Do");
user_pref("mailnews.tags.$label5.color", "#993399");
user_pref("mailnews.tags.$label5.tag", "Later");
user_pref("mailnews.tags.version", 2);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("places.database.lastMaintenance", 1735370957);
user_pref("privacy.purge_trackers.date_in_cookie_database", "0");
user_pref("services.settings.clock_skew_seconds", -15101);
user_pref("services.settings.last_etag", "\"1648185887941\"");
user_pref("services.settings.last_update_seconds", 1735385504);
user_pref("services.settings.thunderbird.hijack-blocklists.last_check", 1735385504);
user_pref("services.settings.thunderbird.search-config.last_check", 1735385504);
user_pref("services.settings.thunderbird.url-classifier-skip-urls.last_check", 1735385504);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1735370957);
user_pref("toolkit.startup.last_success", 1735370371);
user_pref("toolkit.telemetry.cachedClientID", "b3a9cf11-1b58-44d7-a3ea-cba853944f73");
user_pref("toolkit.telemetry.previousBuildID", "20241009170210");
